// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, OcrProcessOcrData, OcrProcessOcrResponse, OcrGetOcrResultsData, OcrGetOcrResultsResponse, OcrGetOcrResultData, OcrGetOcrResultResponse, OcrUpdateOcrResultData, OcrUpdateOcrResultResponse, OcrDeleteOcrResultData, OcrDeleteOcrResultResponse, OcrUpdateWaybillInfoData, OcrUpdateWaybillInfoResponse, OcrUpdateAuditStatusData, OcrUpdateAuditStatusResponse, OcrDownloadOcrTextData, OcrDownloadOcrTextResponse, OcrUploadWaybillData, OcrUploadWaybillResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class OcrService {
    /**
     * Process Ocr
     * Process OCR on uploaded image file.
     *
     * Args:
     * image_file: Image file to process
     * language: OCR language (default: 'ch')
     * use_angle_cls: Whether to use document orientation classification
     * use_dilation: Whether to use dilation processing
     * confidence_thresh: Text recognition confidence threshold (0-1)
     *
     * Returns:
     * OCR processing result
     * @param data The data for the request.
     * @param data.formData
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static processOcr(data: OcrProcessOcrData): CancelablePromise<OcrProcessOcrResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ocr/process',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Ocr Results
     * Get OCR results with pagination and filtering.
     *
     * Args:
     * skip: Number of records to skip
     * limit: Maximum number of records to return
     * waybill_number: Optional waybill number filter
     * carrier: Optional carrier filter
     * recipient: Optional recipient filter
     * audit_status: Optional audit status filter
     * upload_date_start: Optional upload date start filter (YYYY-MM-DD)
     * upload_date_end: Optional upload date end filter (YYYY-MM-DD)
     * shipping_date_start: Optional shipping date start filter (YYYY-MM-DD)
     * shipping_date_end: Optional shipping date end filter (YYYY-MM-DD)
     * delivery_date_start: Optional delivery date start filter (YYYY-MM-DD)
     * delivery_date_end: Optional delivery date end filter (YYYY-MM-DD)
     *
     * Returns:
     * Paginated OCR results
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.waybillNumber
     * @param data.carrier
     * @param data.recipient
     * @param data.auditStatus
     * @param data.uploadDateStart
     * @param data.uploadDateEnd
     * @param data.shippingDateStart
     * @param data.shippingDateEnd
     * @param data.deliveryDateStart
     * @param data.deliveryDateEnd
     * @returns OCRRecordsPublic Successful Response
     * @throws ApiError
     */
    public static getOcrResults(data: OcrGetOcrResultsData = {}): CancelablePromise<OcrGetOcrResultsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ocr/results',
            query: {
                skip: data.skip,
                limit: data.limit,
                waybill_number: data.waybillNumber,
                carrier: data.carrier,
                recipient: data.recipient,
                audit_status: data.auditStatus,
                upload_date_start: data.uploadDateStart,
                upload_date_end: data.uploadDateEnd,
                shipping_date_start: data.shippingDateStart,
                shipping_date_end: data.shippingDateEnd,
                delivery_date_start: data.deliveryDateStart,
                delivery_date_end: data.deliveryDateEnd
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Ocr Result
     * Get specific OCR result by ID.
     *
     * Args:
     * record_id: OCR record UUID
     *
     * Returns:
     * OCR record details
     * @param data The data for the request.
     * @param data.recordId
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static getOcrResult(data: OcrGetOcrResultData): CancelablePromise<OcrGetOcrResultResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ocr/results/{record_id}',
            path: {
                record_id: data.recordId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Ocr Result
     * Update specific OCR result by ID.
     *
     * Args:
     * record_id: OCR record UUID
     * record_update: Updated record data
     *
     * Returns:
     * Updated OCR record
     * @param data The data for the request.
     * @param data.recordId
     * @param data.requestBody
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static updateOcrResult(data: OcrUpdateOcrResultData): CancelablePromise<OcrUpdateOcrResultResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/ocr/results/{record_id}',
            path: {
                record_id: data.recordId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Ocr Result
     * Delete specific OCR result by ID.
     *
     * Args:
     * record_id: OCR record UUID
     *
     * Returns:
     * Success message
     * @param data The data for the request.
     * @param data.recordId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteOcrResult(data: OcrDeleteOcrResultData): CancelablePromise<OcrDeleteOcrResultResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/ocr/results/{record_id}',
            path: {
                record_id: data.recordId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Waybill Info
     * Update waybill information for specific OCR record.
     *
     * Args:
     * record_id: OCR record UUID
     * waybill_number: Waybill number
     * carrier: Carrier/logistics company
     * shipping_date: Shipping date (YYYY-MM-DD)
     * recipient: Recipient name
     * delivery_date: Delivery date (YYYY-MM-DD)
     * upload_date: Upload date (YYYY-MM-DD)
     * uploader: Uploader name
     *
     * Returns:
     * Updated OCR record
     * @param data The data for the request.
     * @param data.recordId
     * @param data.requestBody
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static updateWaybillInfo(data: OcrUpdateWaybillInfoData): CancelablePromise<OcrUpdateWaybillInfoResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/ocr/results/{record_id}/waybill',
            path: {
                record_id: data.recordId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Audit Status
     * Update audit status for specific OCR record.
     *
     * Args:
     * record_id: OCR record UUID
     * audit_status: New audit status (未审核/已审核/审核通过/审核不通过)
     *
     * Returns:
     * Updated OCR record
     * @param data The data for the request.
     * @param data.recordId
     * @param data.requestBody
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static updateAuditStatus(data: OcrUpdateAuditStatusData): CancelablePromise<OcrUpdateAuditStatusResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/ocr/results/{record_id}/audit',
            path: {
                record_id: data.recordId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Download Ocr Text
     * Download OCR result as text file.
     *
     * Args:
     * record_id: OCR record UUID
     *
     * Returns:
     * Download information
     * @param data The data for the request.
     * @param data.recordId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadOcrText(data: OcrDownloadOcrTextData): CancelablePromise<OcrDownloadOcrTextResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ocr/download/{record_id}',
            path: {
                record_id: data.recordId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload Waybill
     * 上传面单图片并进行OCR识别
     *
     * 这是专门为面单管理新增按钮设计的接口，
     * 会自动进行OCR处理。
     *
     * Args:
     * image_file: 面单图片文件
     *
     * Returns:
     * OCR识别结果
     * @param data The data for the request.
     * @param data.formData
     * @returns OCRRecordPublic Successful Response
     * @throws ApiError
     */
    public static uploadWaybill(data: OcrUploadWaybillData): CancelablePromise<OcrUploadWaybillResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ocr/upload-waybill',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
}