"""Update models with OCR and waybill features

Revision ID: 30edc268fee8
Revises: ebaec446304d
Create Date: 2025-07-29 16:03:56.792465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30edc268fee8'
down_revision = 'ebaec446304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_records', sa.Column('waybill_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('ocr_records', sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('ocr_records', sa.Column('shipping_date', sa.DateTime(), nullable=True))
    op.add_column('ocr_records', sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('ocr_records', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    op.add_column('ocr_records', sa.Column('upload_date', sa.DateTime(), nullable=True))
    op.add_column('ocr_records', sa.Column('uploader', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('ocr_records', sa.Column('audit_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, server_default='未审核'))
    op.create_index(op.f('ix_ocr_records_waybill_number'), 'ocr_records', ['waybill_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_records_waybill_number'), table_name='ocr_records')
    op.drop_column('ocr_records', 'audit_status')
    op.drop_column('ocr_records', 'uploader')
    op.drop_column('ocr_records', 'upload_date')
    op.drop_column('ocr_records', 'delivery_date')
    op.drop_column('ocr_records', 'recipient')
    op.drop_column('ocr_records', 'shipping_date')
    op.drop_column('ocr_records', 'carrier')
    op.drop_column('ocr_records', 'waybill_number')
    # ### end Alembic commands ###
