"""add_ocr_records_table

Revision ID: ebaec446304d
Revises: 1a31ce608336
Create Date: 2025-07-28 11:04:48.709429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebaec446304d'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_records',
    sa.Column('device_sn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('result_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('image_format', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('use_angle_cls', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detection_boxes', sa.JSON(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_records_device_sn'), 'ocr_records', ['device_sn'], unique=False)
    op.create_index(op.f('ix_ocr_records_scan_time'), 'ocr_records', ['scan_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_records_scan_time'), table_name='ocr_records')
    op.drop_index(op.f('ix_ocr_records_device_sn'), table_name='ocr_records')
    op.drop_table('ocr_records')
    # ### end Alembic commands ###
